#!/bin/bash
# Quick reference - All commands for the veille system

echo "=== VEILLE SYSTEM - QUICK COMMANDS ==="
echo ""
echo "1. CONFIGURATION UI (Web Dashboard)"
echo "   streamlit run streamlit_app.py"
echo "   → Open http://localhost:8501"
echo ""
echo "2. COLLECT ARTICLES (RSS Feeds)"
echo "   python demo/run_collectors.py"
echo "   → Collects from 4 configured feeds"
echo ""
echo "3. GENERATE SYNTHESIS (Structured Notes)"
echo "   python -c \""
echo "   from watcher.agents.synthesizer import Synthesizer"
echo "   from watcher.storage.store import Storage"
echo "   storage = Storage('watcher.db')"
echo "   items = storage.get_recent_items_full(5)"
echo "   syn = Synthesizer(use_llm=False)"
echo "   note = syn.synthesize("
echo "       topic='AI',"
echo "       period='Today',"
echo "       context='Tech monitoring',"
echo "       items=items,"
echo "       db_path='watcher.db'"
echo "   )"
echo "   print(note)"
echo "   \""
echo ""
echo "4. HISTORICAL ANALYSIS (Period Comparison)"
echo "   python demo/history_report.py --compare"
echo "   → Compare current vs previous 30 days"
echo ""
echo "5. HISTORICAL REPORTS (Multi-Week)"
echo "   python demo/history_report.py --weeks 4"
echo "   → Generate 4-week breakdown"
echo ""
echo "6. CUSTOM PERIOD ANALYSIS"
echo "   python demo/history_report.py --period 14"
echo "   → Analyze last 14 days"
echo ""
echo "7. RUN INTEGRATION TESTS"
echo "   python test_historical_analysis.py"
echo "   → Verify all components"
echo ""
echo "8. SCHEDULE DAILY COLLECTION (Cron)"
echo "   0 9 * * * cd $(pwd) && .venv/bin/python demo/run_collectors.py"
echo "   → Collect articles every day at 9 AM"
echo ""
echo "9. SCHEDULE WEEKLY REPORTS (Cron)"
echo "   0 10 * * 0 cd $(pwd) && .venv/bin/python demo/history_report.py --weeks 1"
echo "   → Generate weekly report every Sunday at 10 AM"
echo ""
echo "=== DOCUMENTATION ==="
echo "  QUICK_START.md                    - Quick reference guide"
echo "  COMPLETION_REPORT.md              - Final implementation summary"
echo "  GAP_ANALYSIS_COMPLETE.md          - Detailed gap resolution"
echo "  HISTORICAL_ANALYSIS_IMPLEMENTATION.md - Technical documentation"
echo ""
